version: '3'
services:
  #app:
  #  build: .
  #  ports:
  #   - "3000:3000"
  #depends_on:
  # - postgres
  #environment:
  #- DATABASE_URL=postgres://nexabuild:nexabuild@postgres:5432/nexabuild

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nexabuild
      POSTGRES_PASSWORD: nexabuild
      POSTGRES_DB: nexabuild
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
